CREATE DATABASE  IF NOT EXISTS `FLIPKART`;

USE `FLIPKART`;

CREATE TABLE IF NOT EXISTS `BUYERINFO` (
  `SKEY` int unsigned NOT NULL AUTO_INCREMENT,
  `MOBILE_NUM` varchar(10) NOT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `NAME` varchar(45) NOT NULL,
  `PASSWORD` varchar(45) NOT NULL,
  `DOB` date NOT NULL,
  PRIMARY KEY (`SKEY`),
  UNIQUE KEY `MOBILE_NUM_UNIQUE` (`MOBILE_NUM`),
  UNIQUE KEY `EMAIL_UNIQUE` (`EMAIL`)
);

CREATE TABLE IF NOT EXISTS `CATEGORY` (
  `SKEY` int unsigned NOT NULL AUTO_INCREMENT,
  `CAT_ID` int unsigned NOT NULL,
  `DESC` varchar(255) NOT NULL,
  PRIMARY KEY (`SKEY`),
  UNIQUE KEY `CAT_ID_UNIQUE` (`CAT_ID`)
);

CREATE TABLE IF NOT EXISTS `SUBCATEGORY` (
  `SKEY` int unsigned NOT NULL AUTO_INCREMENT,
  `SUBCAT_ID` int unsigned NOT NULL,
  `CAT_ID` int unsigned NOT NULL,
  `DESC` varchar(255) NOT NULL,
  PRIMARY KEY(`SKEY`),
  UNIQUE KEY `CAT_ID_UNIQUE` (`CAT_ID`),
  UNIQUE KEY `SUBCAT_ID_UNIQUE` (`SUBCAT_ID`),
  FOREIGN KEY(`CAT_ID`) REFERENCES CATEGORY(`CAT_ID`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `ITEMINFO` (
  `SKEY` int unsigned NOT NULL AUTO_INCREMENT,
  `ITEM_ID` int unsigned NOT NULL,
  `NAME` varchar(30) NOT NULL,
  `DESC` varchar(255) NOT NULL,
  `IMG_URL` varchar(200) NOT NULL,
  `CAT_ID` int unsigned NOT NULL,
  `SUBCAT_ID` int unsigned NOT NULL,
  PRIMARY KEY (`SKEY`),
  UNIQUE KEY `ITEM_ID_UNIQUE` (`ITEM_ID`),
  FOREIGN KEY (`CAT_ID`) REFERENCES CATEGORY(`CAT_ID`) ON DELETE CASCADE,
  FOREIGN KEY (`SUBCAT_ID`) REFERENCES SUBCATEGORY(`SUBCAT_ID`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `SELLER` (
  `SKEY` int unsigned NOT NULL AUTO_INCREMENT,
  `SELLER_ID` int unsigned NOT NULL,
  `MOBILE_NUM` varchar(10) NOT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `NAME` varchar(45) NOT NULL,
  `PASSWORD` varchar(45) NOT NULL,
  PRIMARY KEY (`SKEY`),
  UNIQUE KEY `SELLER_ID_UNIQUE` (`SELLER_ID`),
  UNIQUE KEY `MOBILE_NUM_UNIQUE` (`MOBILE_NUM`),
  UNIQUE KEY `EMAIL_UNIQUE` (`EMAIL`)
);

CREATE TABLE IF NOT EXISTS `ITEM` (
  `SKEY` int unsigned NOT NULL AUTO_INCREMENT,
  `ITEM_ID` int unsigned NOT NULL,
  `SELLER_ID` int unsigned NOT NULL,
  `PRICE` float(8,2) unsigned NOT NULL,
  PRIMARY KEY (`SKEY`),
  FOREIGN KEY (`SELLER_ID`) REFERENCES SELLER(`SELLER_ID`) ON DELETE CASCADE,
  FOREIGN KEY (`ITEM_ID`) REFERENCES ITEMINFO(`ITEM_ID`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `DEAL` (
  `SKEY` int unsigned NOT NULL AUTO_INCREMENT,
  `CAT_ID` int unsigned NOT NULL,
  `DISCOUNT_PERCENTAGE` int unsigned NOT NULL,
  PRIMARY KEY(`SKEY`),
  CONSTRAINT DISCOUNT_CHK CHECK (DISCOUNT_PERCENTAGE >= 0 AND DISCOUNT_PERCENTAGE <= 100),
  FOREIGN KEY(`CAT_ID`) REFERENCES CATEGORY(`CAT_ID`) ON DELETE CASCADE
);